# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ryw03\Desktop\工资结算系统\ui\主框架.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget()
        self.treeWidget.setStyleSheet("QTreeWidget{\n"
                                      "    background-color: #5B677A;\n"
                                      " \n"
                                      "    /* set the font properties*/\n"
                                      "    font-size:17px;\n"
                                      "    color: white;\n"
                                      "}\n"
                                      " \n"
                                      "QTreeWidget::item{\n"
                                      "    margin:13px;\n"
                                      "    background: #5B677A;\n"
                                      "    background-clip: margin;\n"
                                      "}\n"
                                      " \n"
                                      " \n"
                                      "QTreeWidget::branch{\n"
                                      "    background:#5B677A;\n"
                                      "    }\n"
                                      " \n"
                                      " \n"
                                      "QTreeView::item:hover {\n"
                                      "    background: rgb(69, 187, 217);;\n"
                                      "}\n"
                                      " \n"
                                      "QTreeView::item:selected:active{\n"
                                      "    background: rgb(63, 147, 168);\n"
                                      "}\n"
                                      " \n"
                                      "QTreeView::item:selected:!active {\n"
                                      "    background: rgb(63, 147, 168);\n"
                                      "}\n"
                                      " \n"
                                      " \n"
                                      "QTreeWidget::branch:closed:has-children:!has-siblings,\n"
                                      "QTreeWidget::branch:closed:has-children:has-siblings {\n"
                                      "    border-image: none;\n"
                                      "    image: url(:/image/plus.png);\n"
                                      "}\n"
                                      " \n"
                                      " \n"
                                      "QTreeWidget::branch:open:has-children:!has-siblings,\n"
                                      "QTreeWidget::branch:open:has-children:has-siblings  {\n"
                                      "    border-image: none;\n"
                                      "    image: url(:/image/minus.png);\n"
                                      "}\n"
                                      " \n"
                                      "QTreeWidget::branch:!has-children:has-siblings:adjoins-item{\n"
                                      "    border-image:none;\n"
                                      "    image:url(:/image/test.png);\n"
                                      "    }\n"
                                      " \n"
                                      "QTreeWidget::branch:!has-children:!has-siblings:adjoins-item{\n"
                                      "    border-image:none;\n"
                                      "    image:url(:/image/test.png);\n"
                                      "    }")
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.horizontalLayout_2.addWidget(self.treeWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_3.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 14pt \"宋体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 12pt \"宋体\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.current_username_label = QtWidgets.QLabel(self.centralwidget)
        self.current_username_label.setStyleSheet("font: 12pt \"宋体\";")
        self.current_username_label.setObjectName("current_username_label")
        self.horizontalLayout.addWidget(self.current_username_label)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("font: 12pt \"宋体\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.current_role_label = QtWidgets.QLabel(self.centralwidget)
        self.current_role_label.setStyleSheet("font: 12pt \"宋体\";")
        self.current_role_label.setObjectName("current_role_label")
        self.horizontalLayout.addWidget(self.current_role_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("font: 12pt \"宋体\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_2.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(1, 5)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "主页"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "系统配置"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "参数配置表"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "系统用户表"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "基本信息"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "员工基本信息表"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "岗位基本信息表"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "基本工资配置"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "专业技术职务津贴表"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "艰苦边远地区补贴表"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "知识分子补贴表"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "岗位等级表"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "员工薪级工资套改表"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "绩效配置"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "岗位积分定价表"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "绩效薪酬延期支付比例表"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "绩效工资表"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "季度填报"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "部门积分表"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "员工积分表"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "月度填报"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "月度填报表"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "工资结果"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("MainWindow", "员工工资表"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "XX公司工资结算系统"))
        self.label_2.setText(_translate("MainWindow", "用户:"))
        self.current_username_label.setText(_translate("MainWindow", "张三"))
        self.label_4.setText(_translate("MainWindow", "角色:"))
        self.current_role_label.setText(_translate("MainWindow", "普通用户"))
        self.pushButton.setText(_translate("MainWindow", "登出"))
